#!/usr/bin/env python3
# Termux Network Intelligence Toolkit
# Author: Folorunso George 
# Description: Scans your Wi-Fi network, lists all connected devices,
#              checks common open ports, and generates an HTML report.

import subprocess
import socket
import time
import json
from datetime import datetime

# ------------------------------------------------------------
# 1. Get local IP address and subnet
# ------------------------------------------------------------
def get_local_ip():
    try:
        # Get default route interface IP
        result = subprocess.getoutput("ip route | grep -oP 'src \\K[0-9.]+' | head -1")
        if result and result != "":
            return result
        # Fallback: use hostname resolution
        hostname = socket.gethostname()
        return socket.gethostbyname(hostname)
    except:
        return "192.168.1.1"

# ------------------------------------------------------------
# 2. Ping sweep to find live hosts
# ------------------------------------------------------------
def scan_network(subnet_prefix):
    """subnet_prefix like '192.168.1' """
    live_hosts = []
    print(f"[*] Scanning {subnet_prefix}.0/24 ...")
    for i in range(1, 255):
        ip = f"{subnet_prefix}.{i}"
        # Ping with 1 second timeout, discard output
        res = subprocess.call(f"ping -c 1 -W 1 {ip} > /dev/null 2>&1", shell=True)
        if res == 0:
            # Try to get hostname via nslookup
            hostname = subprocess.getoutput(f"nslookup {ip} 2>/dev/null | grep 'name =' | cut -d= -f2 | head -1").strip()
            if not hostname:
                hostname = ip
            live_hosts.append({"ip": ip, "hostname": hostname})
            print(f"[+] Found: {ip} ({hostname})")
        # Tiny delay to avoid flooding
        time.sleep(0.01)
    return live_hosts

# ------------------------------------------------------------
# 3. Port scan on common ports (optional but impressive)
# ------------------------------------------------------------
def scan_ports(ip, ports=None):
    if ports is None:
        ports = [21,22,23,80,443,445,8080,3306,3389]
    open_ports = []
    for port in ports:
        try:
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.settimeout(0.3)
            result = sock.connect_ex((ip, port))
            if result == 0:
                open_ports.append(port)
            sock.close()
        except:
            pass
    return open_ports

# ------------------------------------------------------------
# 4. Generate HTML report (saved to /sdcard/)
# ------------------------------------------------------------
def generate_report(hosts, filename="network_report.html"):
    # Build rows for each host
    rows = ""
    for h in hosts:
        ports = scan_ports(h["ip"])
        ports_str = ", ".join(str(p) for p in ports) if ports else "None"
        rows += f"""
        <tr>
            <td>{h['ip']}</td>
            <td>{h['hostname']}</td>
            <td>{ports_str}</td>
        </tr>
        """
    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Network Scan Report</title>
    <style>
        body {{ background: #0a0a0a; color: #0f0; font-family: 'Courier New', monospace; padding: 20px; }}
        h1 {{ color: #0f0; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
        th, td {{ border: 1px solid #0f0; padding: 8px; text-align: left; }}
        th {{ background: #1a1a1a; }}
        .footer {{ margin-top: 30px; font-size: 0.8em; color: #666; }}
    </style>
</head>
<body>
    <h1>📡 Termux Network Intelligence Toolkit</h1>
    <p>Scan completed at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    <p>Total devices found: {len(hosts)}</p>
    <table>
        <tr><th>IP Address</th><th>Hostname</th><th>Open Ports (common)</th></tr>
        {rows}
    </table>
    <div class="footer">Generated by Termux on Android | No root required | For educational use on your own network</div>
</body>
</html>"""
    # Save to internal storage (accessible via file manager)
    output_path = "/sdcard/network_report.html"
    with open(output_path, "w") as f:
        f.write(html)
    print(f"[✓] Report saved to {output_path}")
    return output_path

# ------------------------------------------------------------
# 5. Main
# ------------------------------------------------------------
def main():
    print("=" * 50)
    print("Termux Network Intelligence Toolkit")
    print("=" * 50)
    local_ip = get_local_ip()
    print(f"[*] Local IP address: {local_ip}")
    # Extract subnet prefix (first three octets)
    parts = local_ip.split('.')
    if len(parts) >= 3:
        subnet_prefix = ".".join(parts[:3])
    else:
        subnet_prefix = "192.168.1"
    print(f"[*] Scanning subnet: {subnet_prefix}.0/24")
    hosts = scan_network(subnet_prefix)
    print(f"[*] Found {len(hosts)} live device(s).")
    if hosts:
        print("\n[*] Checking open ports on each device (this may take a moment)...")
        for h in hosts:
            ports = scan_ports(h["ip"])
            if ports:
                print(f"    {h['ip']} – open ports: {ports}")
    report_path = generate_report(hosts)
    print(f"\n[✓] Done. Open the HTML report from your phone's file manager or via browser:")
    print(f"    file://{report_path}")

if __name__ == "__main__":
    main()
